service:  wi-todo

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128

plugins:
  - serverless-client-s3

custom:
  client:
    path: /dist
    bucketName: witodo-web
