service: wi-todo

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128  
  region: us-east-1
  vpc:
    securityGroupIds:
      - sg-0a34fd75
    subnetIds:
      - subnet-183b7443
      - subnet-4bd68766
      - subnet-d2a7a19b
      - subnet-242ba018

plugins:
  - serverless-offline
  - serverless-plugin-include-dependencies
  
functions:
  create:
    handler: src/api/todoList/create.create
    events:
      - http:
          path: todoList/create
          method: post
          cors: true

  update:
    handler: src/api/todoList/update.update
    events:
      - http:
          path: todoList/update
          method: put
          cors: true
  
  delete:
    handler: src/api/todoList/delete.delete
    events:
      - http:
          path: todoList/delete
          method: delete
          cors: true

  list:
    handler: src/api/todoList/list.list
    events:
      - http:
          path: todoList/list
          method: get
          cors: true