service: wi-todo

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128

plugins:
  - serverless-offline
  - serverless-plugin-include-dependencies
  
functions:
  create:
    handler: src/todoList/create.create
    events:
      - http:
          path: todoList/create
          method: post
          cors: true

  update:
    handler: src/todoList/update.update
    events:
      - http:
          path: todoList/update
          method: put
          cors: true
  
  delete:
    handler: src/todoList/delete.delete
    events:
      - http:
          path: todoList/delete
          method: delete
          cors: true

  list:
    handler: src/todoList/list.list
    events:
      - http:
          path: todoList/list
          method: get
          cors: true